name: MIKEHARDIE
favicon: null
layout_spectrum: 0.9999811942689121
typography_spectrum: 0.4904017162043601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.11979319993406534
  lightness: 0.9039817238226533
  saturation: 0.3948828012216836
  rhythmicContrast: 0.9345341525040567
purpose: []
